/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Session = IDL.Record({
  'totalBadPostureDuration' : IDL.Nat,
  'threshold' : IDL.Float64,
  'totalGoodPostureDuration' : IDL.Nat,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserSettings = IDL.Record({ 'postureThreshold' : IDL.Float64 });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSession' : IDL.Func([Session], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'getSortedSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Session = IDL.Record({
    'totalBadPostureDuration' : IDL.Nat,
    'threshold' : IDL.Float64,
    'totalGoodPostureDuration' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserSettings = IDL.Record({ 'postureThreshold' : IDL.Float64 });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSession' : IDL.Func([Session], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getSortedSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };